### ISSUE TITLE
Generate a Bingo Card

### ISSUE THREAD

**Issue by pathawks** [AICSC/Coding-Challenges#14]
Generate a Bingo card

**Example:**

``` text
 B  I  N  G  O 
14 20 32 52 71
10 27 42 55 64
 7 23 ** 58 69
11 28 34 56 72
15 25 33 53 66
```

**Comment by ChadH1971** [comment]
That one is pretty complex if you remember from html and Javascript

**Comment by pathawks** [comment]
> That one is pretty complex if you remember from html and Javascript

Oh, [I remember!](http://student.pathawks.com/COMSB74C/unit9/)
