### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by pathawks** [AICSC/Coding-Challenges#20]
Do we want to apply a [free software license](http://en.m.wikipedia.org/wiki/Free_software_license) to all or part of this repository?

While I don’t expect any of our code to show up in the next version of the Linux kernel, other groups/classes might be interested in using some of our challenges.

I don’t see that we have anything to lose, and any attention we can bring to the club would be a positive thing.

Thoughts?

**Comment by asterwolf** [comment]
I don't see a problem with it.. But maybe you should ask @ChadH1971. I'm sure
he'll have a lot more input to give than me. :stuck_out_tongue:

**Comment by ChadH1971** [comment]
I'm thinking that if we do, then we probably need to let contributors know that their "intellectual property" may be placed into public domain. I don't imagine that any of our challenges will end up being the next competitor to Microsoft and having some community recognition can be a great thing. Let's put this on the agenda for the next meeting. I have a guest speaker lined up for the 17th though, so I don't want the agenda to get too big.

**Comment by pathawks** [comment]
Not exactly "public domain", and many licenses require that the original author be credited in any future modifications of the work. How cool would that be? :neckbeard:

That said, your point still stands: we _must_ make this decision as a group.

**Comment by pathawks** [comment]
Vote has [been approved](http://aicsc.github.io/2015/09/18/minutes.html).

I just need to contact a couple past members to get their permission to open source their code.

**Comment by pathawks** [comment]
Closed via 924d714089e87d2f2c876784cc342e827f39a6ea
